AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: "db.t3.micro"
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: 14.8
      MasterUsername: admin
      MasterUserPassword: secretpassword
      DeletionProtection: false
      DeleteAutomatedBackups: true